name: Test github action bool inputs

on:
  workflow_call:
    inputs:
      passed_true:
        type: boolean
        required: true
      passed_false:
        type: boolean
        required: true
      undefined:
        type: boolean
  workflow_dispatch:
    inputs:
      passed_true:
        type: boolean
        required: true
      default_true:
        type: boolean
        required: true
        default: true
      passed_false:
        type: boolean
        required: true
      default_false:
        type: boolean
        required: true
        default: false
      undefined:
        type: boolean

jobs:
  if-true:
    if: ${{ inputs.passed_true }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-default-true:
    if: ${{ inputs.default_true }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-not-true:
    if: ${{ !inputs.passed_true }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-not-default-true:
    if: ${{ !inputs.default_true }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-false:
    if: ${{ inputs.passed_false }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-default-false:
    if: ${{ inputs.default_false }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-not-false:
    if: ${{ !inputs.passed_false }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"
  
  if-not-default-false:
    if: ${{ !inputs.default_false }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-undefined:
    if: ${{ inputs.undefined }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"

  if-not-undefined:
    if: ${{ !inputs.undefined }}
    runs-on: ubuntu-latest

    steps:
      - name: Print
        run: echo "Hello World"
